Update README.md
PSPDFKit/awesome-pspdfkit pull request #15
Opened 2024-07-08 15:00 UTC by 0mar-K

Added 5 examples for Annotations
Created a new section for Form Creator and added 3 examples

Looping in @ChrisixFlash for review

2024-07-08 15:09 UTC, jdrhyne approved these changes

2024-07-09 07:31 UTC, ChrisixFlash requested changes
Let's remove these 2 and merge the rest!

2024-07-09 07:31 UTC, ChrisixFlash commented on README.md
> +- [Setting Date Locale to the desired format](https://pspdfkit.com/playground?p=eyJ2IjoxLCJzZXR0aW5ncyI6eyJmaWxlTmFtZSI6ImJhc2ljLnBkZiIsImp3dCI6eyJwZXJtaXNzaW9ucyI6WyJyZWFkLWRvY3VtZW50Iiwid3JpdGUiXSw
Let's skip this, discussed it with Eli and it makes little sense to add.

2024-07-09 07:31 UTC, ChrisixFlash commented on README.md
> +- [Generate Bates with the page info dimensions](https://pspdfkit.com/playground?p=eyJ2IjoxLCJzZXR0aW5ncyI6eyJmaWxlTmFtZSI6ImJhc2ljLnBkZiIsImp3dCI6eyJwZXJtaXNzaW9ucyI6WyJyZWFkLWRvY3VtZW50Iiwid3JpdGUi
This we can also skip as it's already being worked on internally: https://pspdfkit.com/guides/web/editor/add-bates-number/

2024-07-09 07:35 UTC, ChrisixFlash approved these changes
Removed the examples I mentioned, good to merge now :)

2024-07-09 08:05 UTC, merged